### ISSUE TITLE
Existing query string causes invalid signed url

### ISSUE THREAD

**Issue by Zugwalt** [jasonsims/aws-cloudfront-sign#10]
If I want to supply a query string in the cloudfront url (e.g.
`https://subdomain.cloudfront.net/path/to/my/file.mov?response-content-disposition=attachment`) when we call `getSignedUrl()` it assumes there are no query parameters and appends the signature query string with another `?`. 

This results in a signed url like `https://subdomain.cloudfront.net/path/to/my/file.mov?response-content-disposition=attachment?Expires=1425700643&...`. (note the double `?` where the second one should be an `&`).

Right now I am working around this with:
```javascript
signedUrl = signedUrl .replace('?response-content-disposition=attachment?', '?response-content-disposition=attachment&');
```

Side note: for cloudfront backed by s3, passing `response-content-disposition=attachment` query string sets the header, so that things like movie files will be downloaded instead of displayed in the browser. This is why I ran into the issue.

**Comment by jasonsims** [comment]
Thanks for reporting this! I'll get it fixed in the next release.
