### ISSUE TITLE
Update npm release

### ISSUE THREAD

**Issue by alterya** [jasonsims/aws-cloudfront-sign#11]
First of all thanks a lot for the effort with the library, very helpful.

Is it possible to update the release on npm? I've just spent few hours trying to find why the example was not working:

```js
var params = {
  keypairId: process.env.PUBLIC_KEY,
  privateKeyString: process.env.PRIVATE_KEY,
  privateKeyPath: '/path/to/private/key',      // Optional. Use as an alternative to privateKeyString.
  expireTime: new Date(2016, 0, 1) // January 1, 2016
}
```

And the reason is that in the npm release `1.1.0` the `expireTime` parameter does not support the format provided in the example.

**Comment by jasonsims** [comment]
Sorry for the confusion! I'll be publishing v2.0.0 shortly which should resolve this.

**Comment by jasonsims** [comment]
I've updated the README so that it's hopefully more descriptive. The `expiretime` param now accepts  a value of milliseconds, moment, or javascript Date object. This is all in v2.0.0 and has been published to npm.

Thanks for your patience!

**Comment by alterya** [comment]
@jasonsims thanks a lot for the prompt reaction!

**Comment by gigablah** [comment]
There should be a warning about this change -- before v2.0.0 the `expireTime` accepted a value in seconds.

**Comment by jasonsims** [comment]
@gigablah I apologize for any issues the changes in v2.0.0 caused you. I thought sticking to semver by ticking the major version for a breaking change and updating the documentation would be enough but I can see how it could be unclear. Would you expect a message in the readme or a warning on the console?

**Comment by gigablah** [comment]
A note in the changelog would be nice. Or a subsection about "upgrading to v2" in the readme perhaps, but that's up to you, as long as the seconds / milliseconds change is documented somewhere :)

**Comment by jasonsims** [comment]
Thanks for the feedback! I'll get that added in.
