### ISSUE TITLE
AWS doesn't like my cloudfront Access Key Id 

### ISSUE THREAD

**Issue by SmoothDialogue** [jasonsims/aws-cloudfront-sign#15]
Hello,

I'm having issues getting this module to work. The way I'm doing this right now is:

1. Restrict access to my cloudfront distribution to my AWS account #
2. Create cloudfront keypair in AWS.
2. Download private .pem file
3. Move pem file `~/.ssh` as `cloudfront.pem`
4. `chmod 600 ~/.ssh/cloudfront.pem`
5. Execute this code in node.js:

   var cf = require('aws-cloudfront-sign')
   var options = {keypairId: {KEYPAIR ID FROM ABOVE}, privateKeyPath: '/Users/{MYUSERNAME}/.ssh/cloudfront.pem', expires: new Date().getTime() + 30000}
    var signedUrl = cf.getSignedUrl('http://my-s3-domain.s3.amazonaws.com/my-great-file.txt', options);
    console.log('Signed URL: ' + signedUrl);

When I visit the signed url, I get a response like this:     

    <Error>
    <Code>InvalidAccessKeyId</Code>
    <Message>
    The AWS Access Key Id you provided does not exist in our records.
    </Message>
    <AWSAccessKeyId>...</AWSAccessKeyId>
    <RequestId>...</RequestId>
    <HostId>.. </HostId>
    </Error>

Then I tried the same steps, but using a standard Access Key Id (not cloudfront access key id):

    <Error>
    <Code>AccessDenied</Code>
    <Message>
    Query-string authentication requires the Signature, Expires and AWSAccessKeyId parameters
    </Message>
    <RequestId>...</RequestId>
    <HostId>...    </HostId>
    </Error>

So I changed line 49 of `cloudfrontUtil.js` from:
    
    'Key-Pair-Id': params.keypairId

to 

    'AWSAccessKeyId': params.keypairId

and I get:

    <Error>
    <Code>SignatureDoesNotMatch</Code>
    <Message>
    The request signature we calculated does not match the signature you provided. Check your key and signing method.
    </Message>
    <AWSAccessKeyId>...</AWSAccessKeyId>
    <StringToSign>GET ... </StringToSign>
    <SignatureProvided>...
    </SignatureProvided>
    <StringToSignBytes>...    </StringToSignBytes>
    <RequestId>...</RequestId>
    <HostId>...    </HostId>
    </Error>

Can you provide any assistance?

**Comment by jcuna** [comment]
Did you ever figure this one out?

**Comment by jasonsims** [comment]
Hey sorry for the delay in response! If you are still seeing this issue ensure that you have used the "Access Key Id" value for the keypairId param and that the key pair has moved to an active state. It takes a few minutes after creation for the keypair to become active.

![screen shot 2016-02-26 at 9 48 02 pm](https://cloud.githubusercontent.com/assets/1484253/13371112/151abb00-dcd3-11e5-952f-19175e59f9e9.png)

**Comment by mewalig** [comment]
The same message shows up if the URL is not correct. Make sure to use the domain specified in the cloudfront distribution description (and not, for example, the Origin Domain Name).
![image](https://user-images.githubusercontent.com/8260442/33865733-fa0aceb2-dec0-11e7-9d62-4c856f655783.png)
