### ISSUE TITLE
Signed Cookies

### ISSUE THREAD

**Issue by LasCondes** [jasonsims/aws-cloudfront-sign#17]
It would be great if you could add signed cookies for CloudFront to your library. This is also a missing piece of the aws-javascript-sdk.

**Comment by reidmweber** [comment]
:+1:

**Comment by jasonsims** [comment]
Thanks for bringing this up. Signed cookies have been added as of 1559a8f8d691cca560cd063cf7bdca5ff746d4cf and will go into the next release.

**Comment by jasonsims** [comment]
Signed cookies are now available in v2.1.0
