### ISSUE TITLE
Issue generating a working signed url.

### ISSUE THREAD

**Issue by vageez** [jasonsims/aws-cloudfront-sign#20]
Good day.
First thing.. thanks for setting up this package! Big help!
I would not mark this as an issue. I am however having trouble generating a working signed URL.

I am successfully generating a URL by following your documentation.
The url however gives me an access/denied message or in some cases missing Missing Key-Pair-Id query parameter or cookie value.

We are not using Cookies. the URL structure seems valid.
?Expires=1452884605&Signature=VOzPlbAGQeCA98Rn60xoLr0qLxyd94j5UfIkRbOfd~6hkIT2uH1RXSvVKPUW1UCfw7CGJ-HTbGQ55lPrjPebdnR3doF36wHNpPN0U2AvItnbPeHt0GqDT0WUIhMZdH0h7uqTw4SZ86sEniJX3x2IZj-UAWpEx7pLJjntStxfBRaHISioVQpZDaEiiKFjamRaTKu6J93dv5EZ7IwJyIgJWfiH3j4GKeJjr6IbfXa08oGNm2O71crmwsUo1U~TCDGz5DyHUoQqyrGHv53VOgtYctzUmoRerfNf1VNpkUPY3vfrfbhgS4joKTZMk0u~D9dYCEEWBWbVhKkVBwxF55tNXw__&Key-Pair-Id=AAHKDHS8JDHKSHDK98KS

I am obviously using the policy that is found in CannedPolicy.js
And filling the policy with my URL and expiry.

However looking at my policy.. I feel like i may be doing something wrong?
Hopefully you could shed some light on my issue.

My last hope is that somehow the policy is not valid...
My policy 

{
 "Version": "2008-10-17",
 "Id": "PolicyForCloudFrontPrivateContent",
 "Statement": [
  {
   "Sid": "1",
   "Effect": "Allow",
   "Principal": {
    "AWS": "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity SOMERANDOMVAL"
   },
   "Action": "s3:GetObject",
   "Resource": "arn:aws:s3:::my-encoded-videos/*"
  }
 ]
}

Thank you :)
Any help is greatly appreciated!

**Comment by jasonsims** [comment]
Hey sorry this issue was overlooked! If you are still having issues please reopen and I'll work with you on finding out what's up.
