### ISSUE TITLE
Having trouble with Signed Cookies

### ISSUE THREAD

**Issue by samhatoum** [jasonsims/aws-cloudfront-sign#23]
So I've setup a CloundFront key pair and I'm able to create the signed cookies using this awesome package.

I'm then setting the cookies correctly under a custom domain.

The CloudFront has the custom domain configured. 

I also opened full access to the S3 origin bucket (for testing purposes).

When I hit CloudFront, I get access denied along with a `RequestId` and a `HostId`.

I also tried to access a single object `index.html` using a signed url and that didn't work either.

Any ideas?

**Comment by jasonsims** [comment]
I'm not sure off the top of my head. Can you see if you are able to even create working signed URLs? That will at least point us in the right direction as to whether there is a problem in your cloudfront setup or with the code.

**Comment by samhatoum** [comment]
yep, just tried that. That's not working so it rules out domain issues etc

**Comment by samhatoum** [comment]
I'm also trying the with `d1xxxxxx.cloudfront.net/index.html` url and also with `my.custom.domain/index.html`

going directly to the 'bucket.on.s3/index.html' works as I opened up access.

I think it's something to do with the CloudFront config. Been at it for hours :)

**Comment by samhatoum** [comment]
So I started the whole process again and this time it worked. So I guess I must have done something wrong.

The difference between the first and second time was that I used my root account the second time instead of using an IAM created super user. Perhaps that had something to do with it but it's inconclusive as there were too many moving parts. 

Thanks for your help
