### ISSUE TITLE
path to key not resolving

### ISSUE THREAD

**Issue by elliotrock** [jasonsims/aws-cloudfront-sign#28]
var options = {expireTime: new Date() +7, keypairId: 'mykeyid', privateKeyPath: 'pk-mykeyid.pem'}

I have the .pem key in the same folder as this module, initially in was in another parent folder where I was trying to load it via:

'../../pk-mykeyid.pem'

With no luck. Please give detail on how this should work please?

Cheers

**Comment by jasonsims** [comment]
What is the error you're getting? The snippet you gave should read the file in as expected. However, I notice you're giving `new Date() + 7` for expireTime which may be causing issues. If you are trying to create a date 7 days from now you'll need to do something more like:
```
// Create a date that's 7 days from now.
var expiry = new Date();
expiry.setDate(expiry.getDate() + 7);

var options = {
  expireTime: expiry
}
```

**Comment by elliotrock** [comment]
Basically it can't see the file or dir:

Error: ENOENT: no such file or directory

I stepped over that with the string option, but it would be cleaner to load in the .pem file :)

Cheers

**Comment by jasonsims** [comment]
You shouldn't need to but does it work if you instead provide `./pk-mykeyid.pem`?

**Comment by elliotrock** [comment]
Tried loading it relative, using that method.

**Comment by jasonsims** [comment]
Did that solve the ENOENT error?

**Comment by elliotrock** [comment]
No sorry.

**Comment by jasonsims** [comment]
Can you paste the file structure of your app here?

**Comment by elliotrock** [comment]
Ok, I did try a few ways:

-posts/
  -video/
    video.js <- where my aws-cloudfront-sign code is
    pk-mykeyid.pem

Thanks,

**Comment by jasonsims** [comment]
Can you confirm if you are able to run the following without error?
```
$ cd <app workspace>
$ node
> console.log(fs.readFileSync('pk-mykeyid.pem').toString())
```

**Comment by jasonsims** [comment]
Resolving this for now as there doesn't seem to be an issue with the code.
