### ISSUE TITLE
Setup details for CloudFront RTMP

### ISSUE THREAD

**Issue by joshuar500** [jasonsims/aws-cloudfront-sign#31]
I am wondering what the exact steps are before creating the Signed RTMP urls. At the moment, it looks as though I have everything set up and unsigned RTMP urls seem to work fine. The problem I am having is that I cannot get signed urls working despite various efforts. I am wondering if it is in the configuration on AWS side but I cannot be entirely sure.

I wondering if it could be possible to list the steps to make sure the configuration is set up correctly when using signed rtmp urls. For example, clicking the restrict viewer access, and enabling trusted users, etc., etc. The setup for HTTP is different than RTMP and this seems crucial...

Thank you much.

**Comment by jasonsims** [comment]
I believe the setup in AWS is the same for both. Are you able to create a signed url to some static file? Once that's working RTMP should work also.

**Comment by jasonsims** [comment]
I recommend migrating to the aws-sdk which now has full signature support.
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CloudFront/Signer.html
