### ISSUE TITLE
S3 Custom Policy

### ISSUE THREAD

**Issue by aleclarson** [jasonsims/aws-cloudfront-sign#32]
Do you know if I could use an S3 Custom Policy to sign a CloudFront url (assuming CloudFront is correctly "hooked up" to S3)? 

Also, can CNAMEs be signed, or does it have to be a CloudFront url specifically?

**Comment by jasonsims** [comment]
You should be able to sign CNAMEs without and issue. However, only one of the two custom policy parameters is supported at the moment. This is `IpAddress` via the [ipRange](https://github.com/jasonsims/aws-cloudfront-sign/blob/a8d5579f7cbaa5e0ae737dd063300f9128aa8d6a/README.md#options) option.
