### ISSUE TITLE
Setting signed cookies and verification

### ISSUE THREAD

**Issue by abumere** [jasonsims/aws-cloudfront-sign#35]
So i've been generating signed cookies and have been setting them like so: 

```
exports.signedUrl = function (req, res) {
  var options = {
    keypairId: config.cloudFrontAccessKeyId,
    privateKeyPath: config.cloudFrontSecretKeyPath,
    expireTime: new Date().getTime() + 1800000,
  };
 
  var signedCookies = cf.getSignedCookies('http://cdn.learningesan.com/images/*', options);
  console.log('Signed URL: ' + signedUrl);

  for(var cookieId in signedCookies) {
    res.cookie(cookieId, signedCookies[cookieId]);

  }
  console.log(res);
  res.status(200);
};
```

Back on my client side Im trying to display a image on the CDN in an image tag 
`<img src="http://cdn.learningesan.com/images/circle.png" >
`
For some reason I am still getting a 403 Forbidden error. 

How can I verify the cookies are properly set in the browser?

**Comment by jasonsims** [comment]
Your implementation looks ok. Are you able to successfully use `getSignedUrl` for an image? This will at least let us know if there are any issues in the cloudfront setup.

**Comment by aldegoeij** [comment]
Hi! Experiencing same issue, signedUrl **works fine**, signedCookie keeps giving `Missing Key-Pair-Id query parameter or cookie value` error.

My setup:

```
https://auth.domain.tld/auth -- API GW with Lambda Set-Cookie-ing on request
https://site.domain.tld/index.html  -- open page with 'click to authenticate'
https://site.domain.tld/beta/site.html  -- restricted path behind signed/url/cookie
```

Separate CloudFront Behaviour on `/beta/site.html` with `Restrict Viewer Access`.

Code (Lambda behind API Gateway on the same domain as the CloudFront + S3):

```javascript
var privateKeyString = '----XXXXX----'
var options = {keypairId: 'XXXXX', privateKeyString: privateKeyString}
var signedCookies = cf.getSignedCookies('https://site.domain.tld/beta/*', options);
var signedUrl = cf.getSignedUrl('https://site.domain.tld/beta/site.html', options);

// Create necessary cookies:
for(var cookieId in signedCookies) {
    console.log(cookieId, signedCookies[cookieId]);
    // res.cookie(cookieId, signedCookies[cookieId]);
}

// Set generic cookie options
const options2 = '; Domain=.domain.tld; Path=/; HttpOnly; Secure;'

var response = {
    statusCode: 303,
    message: 'Authentication successful',
    res: {
        'Set-Cookie': 'CloudFront-Policy=' + signedCookies['CloudFront-Policy'] + options2,
        'SEt-Cookie': 'CloudFront-Signature=' + signedCookies['CloudFront-Signature'] + options2,
        'SET-Cookie': 'CloudFront-Key-Pair-Id=' + signedCookies['CloudFront-Signature'] + options2,
        'Location': 'https://site.domain.tld/beta/site.html',
        'Signed-URL': signedUrl
    }
}
    
return callback(null, (response))
```
CORS issues should all be handled by my API GW headers (after lots of debugging).

You can ignore the 303, on API GW I am still giving back 200, cookies are received and stored in the browser, and send with a manual request to `/beta/site.html` but still getting the error.

(the 303 intends to forward someone to `/beta/site.html` on successful auth using the set cookies)

Any help will be greatly appreciated!

**Comment by aldegoeij** [comment]
Can be closed AFAIK
