### ISSUE TITLE
getSignedCookies(): Allow multiple statements in signed cookie policy

### ISSUE THREAD

**Issue by nathaniel-holder** [jasonsims/aws-cloudfront-sign#38]
The [CloudFront policy spec](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-setting-signed-cookie-custom-policy.html) shows that the policy takes an array of statements.  I am not sure if more than one statement is currently supported in CloudFront, but according to [this aws-sdk issue commit comment](https://github.com/aws/aws-sdk-go/issues/505#issuecomment-171816195), it does.  Can getSignedCookies() be changed to accommodate this?

Thanks for a great library, it really helped me out!

~Nathaniel

**Comment by jasonsims** [comment]
I recommend migrating to the aws-sdk which now has full signature support.
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CloudFront/Signer.html
