### ISSUE TITLE
Want to use this to post to Cloudfront

### ISSUE THREAD

**Issue by thinkadi** [jasonsims/aws-cloudfront-sign#39]
Hello,

Can you please let me know if it's possible to use this module to post files to S3 through Cloudfront Signed URLs? If yes, can you please give me an example as to how it works? Thanks!

Adi

**Comment by jasonsims** [comment]
I recommend migrating to the aws-sdk which now has full signature support.
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CloudFront/Signer.html
