### ISSUE TITLE
Is there still a need for this plugin?

### ISSUE THREAD

**Issue by hubdotcom** [jasonsims/aws-cloudfront-sign#40]
This is now supported in the native SDK? 
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CloudFront/Signer.html

**Comment by jasonsims** [comment]
Thanks for pointing this out. It looks like support for cloudfront signatures was added last year in 
https://github.com/aws/aws-sdk-js/issues/618

I'll work to deprecate this module.

**Comment by hubdotcom** [comment]
Not just yet, seems like the aws-sdk is not ready for prime time. The docs are limited and it appears canned policies don't generate correct URL's. In contrast, aws-cloudfront-sign is working nicely
