### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by marabesi** [jasonsims/aws-cloudfront-sign#61]
Hello there,

Is this repo being maintaned? I know from npm that it has 22k monthly downloads, but on the other hand, the merge requests are open for a while.

I am interested in maintain this repo (if needed), let me know what I should do if that is the case.

**Comment by jasonsims** [comment]
Hi @marabesi , thanks for reaching out. This is no longer maintained as I believe the AWS SDK has added this functionality. If you would like to take it over I'm happy to transfer ownership to you. Just let me know!

**Comment by MollardMichael** [comment]
Hello @jasonsims 
I'm really lost in the docuementation for aws sdk v3.

How can I generate a CF presigned Url using it ?

**Comment by miccl** [comment]
Hi @MollardMichael,
I needed it for myself, so I share my solution. You can use the [Cloudfront-Signer ](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CloudFront/Signer.html) `aws-sdk` v2. Sadly, it is currently not included in aws-sdk/v3 (see: [#1822](https://github.com/aws/aws-sdk-js-v3/issues/1822)).

Here a short example of how to use it (in typescript):

```
import * as Cloudfront from 'aws-sdk/clients/cloudfront';

const signer: Cloudfront.Signer = new Cloudfront.Signer(
      process.env.CLOUDFRONT_PUBLIC_KEY_ID,
      process.env.CLOUDFRONT_PRIVATE_KEY,
);

const signedUrl = signer.getSignedUrl({
      url: `https://example.com/path/to/your/url.png`,
      expires: Date.now() + URL_EXPIRATION_TIME_IN_MILLISECONDS * 1000,
});
```

Hope that helps :)

**Comment by marabesi** [comment]
@miccl is this just for signedUrls? Do you know if the functionality for cookies have been migrated to aws-sdk as well?

**Comment by marabesi** [comment]
Hey @jasonsims ths for the reply, maybe you could add me as a collaborator? Changing the ownership breaks smtg on npm?

**Comment by miccl** [comment]
> 
> 
> @miccl is this just for signedUrls? Do you know if the functionality for cookies have been migrated to aws-sdk as well?

According to documentation, it is part of the aws-sdk ([Cloudfront-Signer#getSignedCookie](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CloudFront/Signer.html#getSignedCookie-property)). But I only tried the signedUrl method.

**Comment by jasonsims** [comment]
@marabesi I've invited you as a collaborator on this repo in case you still need it.

**Comment by marabesi** [comment]
related https://github.com/jasonsims/aws-cloudfront-sign/pull/54

**Comment by hmomin** [comment]
Hi @jasonsims,

Could you add me as a collaborator as well? I would like to push #58 to the main branch. There is a serious vulnerability in an old lodash dependency that keeps me up at night and this library is the only one that's reliably worked for me in returning signed cookies. Thank you

**Comment by mwgamble** [comment]
> This is no longer maintained as I believe the AWS SDK has added this functionality.

The V2 SDK has this functionality, but the V3 SDK does not as of today.

**Comment by cloudworkpro-dave** [comment]
Hi @jasonsims,

Do you have an idea of when this functionality will be included in v3? It's concerning to me that cloudfront signing hasn't been ported over, given that it's an important part of your services. At the very least I feel like it needs to be called out in the docs of v3 because like me, I'm sure there are a lot of other people trying to figure out what's going on. Would really appreciate the clarity on this. Thanks!

**Comment by DewaldDeJager** [comment]
@jasonsims I'm also interested in collaborating on this project while we wait for support to be added to the AWS SDK v3. This library works great!

**Comment by keithalpichi** [comment]
I have an [open PR](https://github.com/aws/aws-sdk-js-v3/pull/3461) for adding this functionality into the v3 library.

**Comment by jasonsims** [comment]
I'll continue to maintain this repo as long as people want to use it. It is supported in the aws-sdk but it seems like there are cases where using this library is preferred.
