### ISSUE TITLE
Version 2.2.1 Not Released to NPM

### ISSUE THREAD

**Issue by odellcraig** [jasonsims/aws-cloudfront-sign#64]
Hi Jason,

It looks like there is a release (2.2.1) that resolves the npm audit vulnerabilities with lodash that was released in March, but the NPM package version is still at 2.2.0. Would you be able to update the NPM package latest release to 2.2.1?

Best,
Craig

**Comment by camilosegura** [comment]
Hi team, I've been trying to use this package and having an issue with my CI/CD because Lodash version.  Is there any estimated time to deploy it?

**Comment by Ghazgkull** [comment]
@camilosegura I think they just forgot to bump the version number in the package.json when they cut the 2.2.1 release in Github. I submitted a PR which might help. Hopefully @jasonsims takes a look.

**Comment by im-bob-loucans** [comment]
Any chance this will be pushed to npm?

**Comment by ChristianGebhardtCR** [comment]
Any update here? NPM still has the vulnerable version.

**Comment by Neurosis44** [comment]
Any news about this ?
