### ISSUE TITLE
Redundant console.log in published library

### ISSUE THREAD

**Issue by IhorShmidt** [jasonsims/aws-cloudfront-sign#73]
I've installed the latest 3.0.0 version, and it works fine, but there is one catch that is hard to explain to my team. In the published version, there is a `console.log` inside `getSignedUrl` method

`console.log('LETS SIGN SOME SHIT');`

Inside the library itself, here on the GitHub this section is absent, so I assume the library was published on the local machine with this debug code. Could you please release a new version without debug log?

![image](https://github.com/jasonsims/aws-cloudfront-sign/assets/16352598/4e8d3b03-1c03-4de3-bab8-5ce66636deca)

Thanks for the new version of the library without lodash vulnerability, 
Kind regards, ihor

**Comment by jasonsims** [comment]
Sorry about that! It's fixed in v3.0.2

**Comment by IhorShmidt** [comment]
@jasonsims Thanks a lot
