### ISSUE TITLE
Missing Key-Pair-Id query parameter or cookie value

### ISSUE THREAD

**Issue by paschaldev** [jasonsims/aws-cloudfront-sign#74]
I've followed every guide there is to follow, I've done everything right, I've tried to use a private key file as opposed to a private key string but I still get this "Missing Key Pair-Id" error even though it is present in the URL.

AWS Creating Cloudfront Signed URLs
https://aws.amazon.com/blogs/developer/creating-amazon-cloudfront-signed-urls-in-node-js/

I used this guide for generating the key pairs
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-trusted-signers.html#private-content-adding-trusted-signers

The generated URL contains the `Key-pair-Id` but this error still exists. Any help would be appreciated. 

This is a sample URL generated:

https://xyz.cloudfront.net/test-video/Default/HLS/movie.m3u8?Expires=1693438738&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9kMTcxNHBoOXBrbXNlby5jbG91ZGZyb250Lm5ldC9HQkFTR0JPUy9EZWZhdWx0L0hMUy9HQkFTR0JPU183MjAubTN1OCIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY5MzQzODczOH19fV19&Signature=Ph1Plk0Wdvs8jPOV6Jk2E4NHzlaLFPEDy6aYBo3tuKd6vpIXJ8cySpU3upV5hNl8-Q3N979XrTqOKgWXmJGoIAGPlu1FL-q99IGYczv8UBZvPwYCPJgHmrFbwS85A9FK78LP2J0bmMd7ukNhqVXoMYr1adKzcONasKbftQh9AwA9m89W7EN4oRhXYKOS-904BCLzKKnXySlg%7EJW5wcRQTpJlf8o9MuSF305wWXd1iRbuHNUX46rdpHllvxfWIyqpLwICwDFB1Owqo4h0M3nTaHptbQ13o%7EEbOsL2uKLkDy2N%7EmQzDpJeVmzCWPJs549w8gP-tNwSp1sEw1kFdUdCgg__&Key-Pair-Id=dc5ffcdf-144a-4996-83d5-73c98926d8cf

P.S: Before attempting to use signed URLs, I have always used unsigned URL that worked fine: https://xyz.cloudfront.net/test-video/Default/HLS/movie.m3u8

**Comment by paschaldev** [comment]
My bad, I was using the wrong valud for the public ID. Inn my case, I was using the Key group ID instead of the Public Key ID

**Comment by jasonsims** [comment]
@paschaldev glad you got it working!
