### ISSUE TITLE
AccessDenied error 

### ISSUE THREAD

**Issue by vertex** [jasonsims/aws-cloudfront-sign#8]
I keep getting "AccessDenied," with the Message: "Query-string authentication requires the Signature, Expires and AWSAccessKeyId parameters".  

I try to append an AWSAccessKeyId -- first, I tried the one labeled "Access Key ID" from my Cloudfront Keypairs.  Then it returns: "InvalidAccessKeyId" with the Message: "The AWS Access Key Id you provided does not exist in our records."

Then, I tried the main Access Key from my account, and that returns: "SignatureDoesNotMatch" with the Message: "The request signature we calculated does not match the signature you provided. Check your key and signing method."

	var params = {
		keypairId: pub_key,
		privateKeyPath: __dirname + "/pk-{AWSAccessKeyId-fromCFKeypairs}.pem",
		expireTime: moment().add(30, "minutes").unix(),
		Expire: 60
	};
	cf.getSignedUrl("http://{bucket}.s3.amazonaws.com/" +  FILE_KEY, params) + "&AWSAccessKeyId={AWSAccessKeyId-fromCFKeypairs || AWSAccessKeyId-fromAccountCredentials}";`

A strange thing I noticed about this, is the Params require a Keypair ID, which I passed in the contents from  rsa-{AWSAccessKeyId-fromCFKeypairs}.pem recieved from the Cloudfront Keypair tool.  I feel this might refer to the  "Access Key ID" from my Cloudfront Keypairs, but changing that does the same "SignatureDoesNotMatch" error. 

I'm not sure what I'm doing wrong :(  Thank you!

**Comment by jasonsims** [comment]
It should definitely be your cloudfront keypair. Can you confirm that you completed the steps as listed in the [Creating CloudFront Key Pairs for Your Trusted Signers](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-trusted-signers.html#private-content-creating-cloudfront-key-pairs) guide? Also, the ` + &AWSAccessKeyId= ` piece is not needed in the call to `getSignedUrl` since they are pulled from the params by the library. The `Expire` property in your params is also not needed. In your scenario, it should look like
```js
var path = require('path');
var params = {
  keypairId: pub_key,
  privateKeyPath: path.join(__dirname, "pk-{AWSAccessKeyId-fromCFKeypairs}.pem"),
  expireTime: moment().add(30, "minutes").unix()
};
cf.getSignedUrl("http://{bucket}.s3.amazonaws.com/" +  FILE_KEY, params);
```

**Comment by vertex** [comment]
My problems were: keypairId is the string listed under "Cloudfront Key Pairs / Access Key ID" at https://console.aws.amazon.com/iam/home?region=us-east-1#security_credential
The "{bucket}.s3.amazonaws.com/" should be The "Domain Name" under Cloudfront Distrobutions found here: https://console.aws.amazon.com/cloudfront/home?region=us-east-1

**Comment by akshay-scalex** [comment]
@vertex  @jasonsims : I am also facing the same issue.

**Comment by Noedsondutra** [comment]
That's correct @vertex! 
I needed just little adjustments(maybe it's the problem someone else is facing):

If you use CloudFront: 
This part of the code: "http://{bucket}.s3.amazonaws.com/"
Must be: "https://_Domain Name_/_Key of your S3 archive_"

Where:
**1. _Domain name_** -> is founded in your "CloudFront Distributions" under the tab "Domain Name"
**2. _Key of your S3 archive_** ->  is founded when you open your archive on S3, onto the tab "Overview".

Just keep in mind:
**1. keypairId** -> is the key in "CloudFront key pairs", not in "Access keys (access key ID and secret access key)"
**2. privateKeyString** -> is the string written inside your "CloudFront key pair" **private archive** (that must be downloaded when you create the key). Don't use the **public archive**. 
_Note that: this archive is a .pem format, and you may need a reasonable way of extract this string from it. If you use React, a made the .pem archive into .js and put:
let key = `-----BEGIN RSA PRIVATE KEY-----_bodyofthekey_-----END RSA PRIVATE KEY-----` export default key_
**3. privateKeyPath** must not be used if you use **privateKeyString**


Documentation in:
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/AmazonCloudFront_DevGuide.pdf#PrivateContent
Page 118

How to use the AWS package:
https://aws.amazon.com/pt/blogs/developer/creating-amazon-cloudfront-signed-urls-in-node-js/

I hope have helped!
