### ISSUE TITLE
Supplying Javascript date object doesn't work

### ISSUE THREAD

**Issue by Zugwalt** [jasonsims/aws-cloudfront-sign#9]
Documentation suggests we could do something like
```javascript
expireTime: moment().add(expireTimeSec, 'seconds').toDate()
```

However what I really needed to do was pass unix epoch like
```javascript
expireTime: moment().add(expireTimeSec, 'seconds').unix()
```

Either updating docs or converting date to unix epoch would suffice.
Note I was using the http://momentjs.com/ library.

**Comment by jasonsims** [comment]
Yeah the docs def could use some more clarification so thanks for bringing
this up. The current latest version on npm should take a Unix timestamp
though. Coming soon, I'll add a feature that will allow the library to take
either timestamp, JavaScript Date, or moment though.



On Saturday, March 7, 2015, Aaron Silverman <notifications@github.com>
wrote:

> Documentation suggests we could do something like
>
> expireTime: moment().add(expireTimeSec, 'seconds').toDate()
>
> However what I really needed to do was pass unix epoch like
>
> expireTime: moment().add(expireTimeSec, 'seconds').unix()
>
> Either updating docs or converting date to unix epoch would suffice.
> Note I was using the http://momentjs.com/ library.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jasonsims/aws-cloudfront-sign/issues/9>.
>


-- 
Sent from my iPhone

**Comment by Zugwalt** [comment]
Awesome! No worries. Love the module! Just trying to help out by reporting what I found.

**Comment by jasonsims** [comment]
Can you just confirm that supplying a unix timestamp is working for you in the latest version (v1.1.0)? If so, I'll close this and get the docs updated before releasing v1.2.0.

**Comment by Zugwalt** [comment]
Yup! Supplying a unix timestamp (seconds since epoch) works great.

**Comment by jasonsims** [comment]
I've updated the README so that it's hopefully more descriptive. The `expireTime` param is also more flexible now as it accepts a value of milliseconds, moment, or javascript Date object. This is all in v2.0.0 and has been published to npm.

Thanks for your patience!
